//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vapers_Club.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class devolucione
    {
        public int id { get; set; }
        public Nullable<int> cliente { get; set; }
        public Nullable<int> proveedor { get; set; }
        public string razon { get; set; }
    
        public virtual cliente cliente1 { get; set; }
        public virtual proveedore proveedore { get; set; }
    }
}
