//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vapers_Club.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class entregas
    {
        public int id { get; set; }
        public System.DateTime fecha_pedido { get; set; }
        public int id_producto { get; set; }
        public int cantidad { get; set; }
        public int estado { get; set; }
    
        public virtual estados estados { get; set; }
        public virtual productos productos { get; set; }
    }
}
