//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vapers_Club.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producto()
        {
            this.entregas = new HashSet<entrega>();
            this.almacenes = new HashSet<almacene>();
            this.proveedores = new HashSet<proveedore>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public int marca { get; set; }
        public int categoria { get; set; }
        public int cantidad { get; set; }
        public int codigo { get; set; }
        public string unidadmedida { get; set; }
        public Nullable<System.DateTime> vencimiento { get; set; }
        public decimal precio { get; set; }
    
        public virtual categoria categoria1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<entrega> entregas { get; set; }
        public virtual marca marca1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<almacene> almacenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proveedore> proveedores { get; set; }
    }
}
