//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vapers_Club.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_almaprod
    {
        public int idalmacen { get; set; }
        public string nombre_almacen { get; set; }
        public int idprod { get; set; }
        public string nombre { get; set; }
    }
}
