//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vapers_Club.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_devolucion
    {
        public int id { get; set; }
        public Nullable<int> cliente { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public Nullable<int> proveedor { get; set; }
        public string nprove { get; set; }
        public string razon { get; set; }
    }
}
