//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vapers_Club.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_productos
    {
        public int id { get; set; }
        public string Nombre_Producto { get; set; }
        public decimal precio { get; set; }
        public int cantidad { get; set; }
        public string Nombre_Marca { get; set; }
        public string Nombre_Categ { get; set; }
    }
}
